export default {
  address: "23 Thornridge Dr, Thornhill",
  city: "Richmond Hill",
  state: "Ontario",
  images: [
    { id: 0, path: "/imgs/_1.jpg", categories: ["Front"] },
    { id: 1, path: "/imgs/_3.jpg", categories: ["Front", "Driveway"] },
    { id: 2, path: "/imgs/_4.jpg", categories: ["Front", "Driveway"] },
    { id: 3, path: "/imgs/_5.jpg", categories: ["Driveway", "Garage"] },
    { id: 4, path: "/imgs/_6.jpg", categories: ["Main Entrance"] },
    { id: 5, path: "/imgs/_7.jpg", categories: ["Main Entrance"] },
    { id: 6, path: "/imgs/_8.jpg", categories: ["Main Entrance", "Stairs"] },
    { id: 7, path: "/imgs/_9.jpg", categories: ["Main Entrance", "Stairs"] },
    { id: 8, path: "/imgs/_10.jpg", categories: ["Main Entrance", "Stairs"] },
    { id: 9, path: "/imgs/_11.jpg", categories: ["Living"] },
    { id: 10, path: "/imgs/_12.jpg", categories: ["Dinning"] },
    { id: 11, path: "/imgs/_13.jpg", categories: ["Dinning"] },
    { id: 12, path: "/imgs/_14.jpg", categories: ["Celings"] },
    { id: 13, path: "/imgs/_15.jpg", categories: ["Kitchen"] },
    { id: 14, path: "/imgs/_16.jpg", categories: ["Kitchen"] },
    { id: 15, path: "/imgs/_17.jpg", categories: ["Kitchen"] },
    { id: 16, path: "/imgs/_18.jpg", categories: ["Kitchen", "Breakfest"] },
    { id: 17, path: "/imgs/_19.jpg", categories: ["Kitchen"] },
    { id: 18, path: "/imgs/_20.jpg", categories: ["Breakfest"] },
    { id: 19, path: "/imgs/_21.jpg", categories: ["Breakfest", "View"] },
    { id: 20, path: "/imgs/_22.jpg", categories: ["Family"] },
    { id: 21, path: "/imgs/_23.jpg", categories: ["Family", "Fireplace"] },
    { id: 22, path: "/imgs/_24.jpg", categories: ["Family", "Fireplace"] },
    { id: 23, path: "/imgs/_25.jpg", categories: ["Office"] },
    { id: 24, path: "/imgs/_26.jpg", categories: ["Powder Room", "Fireplace"] },
    { id: 25, path: "/imgs/_27.jpg", categories: ["Pool"] },
    { id: 26, path: "/imgs/_28.jpg", categories: ["Pool"] },
    { id: 27, path: "/imgs/_29.jpg", categories: ["Laundry"] },
    {
      id: 28,
      path: "/imgs/_30.jpg",
      categories: ["Stairs", "2nd Floor", "Chandelier"]
    },
    {
      id: 29,
      path: "/imgs/_31.jpg",
      categories: ["Stairs", "2nd Floor", "Chandelier"]
    },
    { id: 30, path: "/imgs/_32.jpg", categories: ["Bedroom", "2nd Floor"] },
    { id: 31, path: "/imgs/_33.jpg", categories: ["Bedroom", "2nd Floor"] },
    { id: 32, path: "/imgs/_34.jpg", categories: ["Bathroom", "2nd Floor"] },
    { id: 33, path: "/imgs/_35.jpg", categories: ["Bedroom", "2nd Floor"] },
    { id: 34, path: "/imgs/_36.jpg", categories: ["Bedroom", "2nd Floor"] },
    { id: 35, path: "/imgs/_37.jpg", categories: ["Bathroom", "2nd Floor"] },
    { id: 36, path: "/imgs/_38.jpg", categories: ["Bathroom", "2nd Floor"] },
    { id: 37, path: "/imgs/_39.jpg", categories: ["Bedroom", "2nd Floor"] },
    { id: 38, path: "/imgs/_40.jpg", categories: ["Bathroom", "2nd Floor"] },
    { id: 39, path: "/imgs/_41.jpg", categories: ["Bedroom", "2nd Floor"] },
    { id: 40, path: "/imgs/_42.jpg", categories: ["Bathroom", "2nd Floor"] },
    { id: 41, path: "/imgs/_43.jpg", categories: ["Living", "2nd Floor"] },
    { id: 42, path: "/imgs/_44.jpg", categories: ["Bathroom", "2nd Floor"] },
    { id: 43, path: "/imgs/_45.jpg", categories: ["Basement", "Gym"] },
    { id: 44, path: "/imgs/_46.jpg", categories: ["Basement", "Bar"] },
    { id: 45, path: "/imgs/_47.jpg", categories: ["Basement"] },
    { id: 46, path: "/imgs/_48.jpg", categories: ["Basement", "Fireplace"] },
    { id: 47, path: "/imgs/_49.jpg", categories: ["Closet", "Basement"] },
    { id: 48, path: "/imgs/_50.jpg", categories: ["Sauna", "Basement"] },
    { id: 49, path: "/imgs/_51.jpg", categories: ["Sauna", "Basement"] },
    { id: 50, path: "/imgs/_52.jpg", categories: ["Gym", "Basement"] },
    { id: 51, path: "/imgs/_53.jpg", categories: ["Bathroom", "Basement"] },
    { id: 52, path: "/imgs/_54.jpg", categories: ["Backyard"] },
    { id: 53, path: "/imgs/_55.jpg", categories: ["Backyard", "Gazibo"] },
    { id: 54, path: "/imgs/_56.jpg", categories: ["Backyard", "Patio"] },
    { id: 55, path: "/imgs/_57.jpg", categories: ["Backyard", "Patio"] }
  ],
  features: ["Pool", "Patio", "Rooftop Deck", "2BR", "3BR"],
  details: [
    "*Luxury&Timeless Extraordinary Elegance On ~ Nearly 1 Acre Lot!! A True Masterpiece French Inspired Palace In The Prestigious Oakbank Pond & Thornhill Country Club Neighbourhood. Gracious Estate Invites Grand Entertaining & Serene Living.*Featuring: An Ambiance Of Unequal Charm. Magnificent Outdoor Living Area W/Panoramic Vistas. Indoor Cabana Pool, Jacuzzi, Bar. Complete Fitness Centre W/Sauna. Walkup Bsmt, Circular Drive W/Gates. 4 Car Garage!!*",
    "Extras:Over 10,000 Sf Of Luxurious Detail & Craftsmanship! A Palacial Estate Of Remarkable Quality!! 10Ft Ceilings. Gorgeous Cathedral Grand Foyer*Skylights*Custom Wood/Iron Railings*Wet Bars*Gas F/Ps*Custom Gourmet Kitchen"
  ],

  zoom: 16,
  center: {
    lat: 43.8125278,
    lng: -79.4276323
  }
};
